version: '3.6'
services:
  book-to-kindle:
    build: 
      context: .
      dockerfile: Dockerfile
    image: book-to-kindle:latest
    container_name: book-to-kindle
    ports:
    - 8443:80



      
    